/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classe.BddProspect;
import static Classe.BddProspect.*;
import static Classe.Controle.*;
import Classe.Prospect;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import static javax.swing.JOptionPane.*;

/**
 * Formulaire du prospect permettant de remplir le schamps pour la création ou la modification d'un prospect
 * 
 * @author Raphaël Frantzen 
 * @version 12
 * Récupération des raisons sociales des prospects
 */
public class formProspect extends javax.swing.JFrame {

    boolean VarCreation;
    
    /**
     * Creates new form formProspect
     */
    public formProspect() {
        initComponents();
        TxtNumProsp.setEditable(false);
    }
    
    //Création d'un formulaire vide pour la création d'un prospect
    public formProspect(boolean ActionCreer)throws Exception{
        initComponents();
        VarCreation = ActionCreer;
        TxtNumProsp.setEditable(false);
        TxtNumProsp.setText(AffDernId());
    }
    
    //Création d'un formulaire préremplie pour la modification d'un prospect
    public formProspect(Prospect LeProspect){
        initComponents();
        TxtNumProsp.setText(Integer.toString(LeProspect.getIdEntrep()));
        TxtRaisSocProsp.setText(LeProspect.getRaisonSociale());
        CmbBoxTypeProsp.setSelectedItem(LeProspect.getTypeEntrep());
        TxtDomaineProsp.setText(LeProspect.getDomaineEntrep());
        TxtAdrProsp.setText(LeProspect.getAdrEntrep());
        TxtTelProsp.setText(LeProspect.getTelEntrep());
        TxtNbEmpProsp.setText(Long.toString(LeProspect.getNbrEmpEntrep()));
        TxtCommentProsp.setText(LeProspect.getCommentaireEntrep());
        TxtChiffAffProsp.setText(Integer.toString(LeProspect.getCaEntrep()));
        TxtDateProspection.setText(LeProspect.getDateProspection().toString());
        CmbBoxInteresse.setSelectedItem(LeProspect.getInteresse());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabDomaineClient = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        TxtCommentProsp = new javax.swing.JTextArea();
        LabNbrEmpProsp = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TxtDomaineProsp = new javax.swing.JTextPane();
        BtnRetourProsp = new javax.swing.JButton();
        BtnConfirmProsp = new javax.swing.JButton();
        LabDateProspection = new javax.swing.JLabel();
        LabInteresse = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TxtDateProspection = new javax.swing.JTextPane();
        TxtNbrEmpClient = new javax.swing.JScrollPane();
        TxtNbEmpProsp = new javax.swing.JTextPane();
        LabRaisonSocialeProsp = new javax.swing.JLabel();
        LabAdrClient = new javax.swing.JLabel();
        LabChiffAffProsp = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtRaisSocProsp = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        TxtAdrProsp = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        TxtChiffAffProsp = new javax.swing.JTextPane();
        LabGestProsp = new javax.swing.JLabel();
        LabTypeProsp = new javax.swing.JLabel();
        LabTelProsp = new javax.swing.JLabel();
        LabCommentaireProsp = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TxtTelProsp = new javax.swing.JTextPane();
        CmbBoxTypeProsp = new javax.swing.JComboBox<>();
        LabNumProsp = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        TxtNumProsp = new javax.swing.JTextPane();
        CmbBoxInteresse = new javax.swing.JComboBox<>();
        LabDateProspection2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabDomaineClient.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabDomaineClient.setText("Domaine Prospect :");

        TxtCommentProsp.setColumns(20);
        TxtCommentProsp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtCommentProsp.setRows(5);
        jScrollPane8.setViewportView(TxtCommentProsp);

        LabNbrEmpProsp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabNbrEmpProsp.setText("Nombre d'Employé :");

        jScrollPane4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jScrollPane4.setViewportView(TxtDomaineProsp);

        BtnRetourProsp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BtnRetourProsp.setText("Retour");
        BtnRetourProsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetourProspActionPerformed(evt);
            }
        });

        BtnConfirmProsp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BtnConfirmProsp.setText("Confirmer");
        BtnConfirmProsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmProspActionPerformed(evt);
            }
        });

        LabDateProspection.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabDateProspection.setText("Date de Prospection :");

        LabInteresse.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabInteresse.setText("Interesse :");

        TxtDateProspection.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jScrollPane7.setViewportView(TxtDateProspection);

        TxtNbEmpProsp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtNbrEmpClient.setViewportView(TxtNbEmpProsp);

        LabRaisonSocialeProsp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabRaisonSocialeProsp.setText("Raison Sociale :");

        LabAdrClient.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabAdrClient.setText("Adresse Prospect :");

        LabChiffAffProsp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabChiffAffProsp.setText("Chiffre d'Affaire :");

        TxtRaisSocProsp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(TxtRaisSocProsp);

        jScrollPane5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jScrollPane5.setViewportView(TxtAdrProsp);

        TxtChiffAffProsp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jScrollPane3.setViewportView(TxtChiffAffProsp);

        LabGestProsp.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        LabGestProsp.setText("Gestion des Prospects");

        LabTypeProsp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabTypeProsp.setText("Type de Prospect :");

        LabTelProsp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabTelProsp.setText("Téléphone Prosp :");

        LabCommentaireProsp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabCommentaireProsp.setText("Commentaires :");

        TxtTelProsp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jScrollPane6.setViewportView(TxtTelProsp);

        CmbBoxTypeProsp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CmbBoxTypeProsp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Privé", "Public" }));

        LabNumProsp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabNumProsp.setText("Numéro Prospect :");

        TxtNumProsp.setEditable(false);
        TxtNumProsp.setBackground(new java.awt.Color(240, 240, 240));
        jScrollPane10.setViewportView(TxtNumProsp);

        CmbBoxInteresse.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CmbBoxInteresse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N", "O" }));

        LabDateProspection2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabDateProspection2.setText("(au format AAAA-MM-JJ)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(LabGestProsp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addComponent(BtnConfirmProsp, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnRetourProsp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabNbrEmpProsp)
                                            .addComponent(LabChiffAffProsp)
                                            .addComponent(LabCommentaireProsp)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(LabRaisonSocialeProsp)
                                                .addComponent(LabNumProsp)
                                                .addComponent(LabTypeProsp))
                                            .addComponent(LabTelProsp))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane10)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(TxtNbrEmpClient, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane6)
                                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabAdrClient)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(CmbBoxTypeProsp, javax.swing.GroupLayout.Alignment.TRAILING, 0, 406, Short.MAX_VALUE)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabDomaineClient)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabInteresse)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(LabDateProspection)))
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LabDateProspection2)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7)
                            .addComponent(CmbBoxInteresse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabGestProsp)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabNumProsp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabRaisonSocialeProsp)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmbBoxTypeProsp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabTypeProsp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabDomaineClient)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabAdrClient)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabTelProsp)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabNbrEmpProsp)
                    .addComponent(TxtNbrEmpClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabChiffAffProsp))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabCommentaireProsp)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabDateProspection)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabDateProspection2)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CmbBoxInteresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabInteresse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRetourProsp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnConfirmProsp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Bouton permettant de confirmer les champs du formulaire prospect pour une création ou une modification
    private void BtnConfirmProspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmProspActionPerformed
        try{
            if(VarCreation){
                //Pour créer un prospect
                GestGuillemet(TxtCommentProsp);
                GestChampNum(TxtNumProsp);
                GestChampNum(TxtNbEmpProsp);
                GestChampNum(TxtChiffAffProsp);
                GestNumTel(TxtTelProsp);
                GestDate(TxtDateProspection);
                DateTimeFormatter formatDate = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                LocalDate dateLocaleCrea = LocalDate.parse(TxtDateProspection.getText(), formatDate);
                Prospect unProspCrea = new Prospect(Integer.parseInt(TxtNumProsp.getText()), TxtRaisSocProsp.getText(), CmbBoxTypeProsp.getSelectedItem().toString(), TxtDomaineProsp.getText(),
                    TxtAdrProsp.getText(), TxtTelProsp.getText(), Long.parseLong(TxtNbEmpProsp.getText()), TxtCommentProsp.getText(), Integer.parseInt(TxtChiffAffProsp.getText()),
                    dateLocaleCrea, CmbBoxInteresse.getSelectedItem().toString());
                unProspCrea.creation();
                showMessageDialog(null, "Le prospect " + TxtNumProsp.getText() + " a été créé.");
            }
            else{
                //Pour modifier un prospect
                GestGuillemet(TxtCommentProsp);
                GestChampNum(TxtNumProsp);
                GestChampNum(TxtNbEmpProsp);
                GestChampNum(TxtChiffAffProsp);
                GestNumTel(TxtTelProsp);
                GestDate(TxtDateProspection);
                DateTimeFormatter formatDate = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                LocalDate dateLocaleCrea = LocalDate.parse(TxtDateProspection.getText(), formatDate);
                Prospect unProspModif = new Prospect(Integer.parseInt(TxtNumProsp.getText()), TxtRaisSocProsp.getText(), CmbBoxTypeProsp.getSelectedItem().toString(), TxtDomaineProsp.getText(),
                    TxtAdrProsp.getText(), TxtTelProsp.getText(), Long.parseLong(TxtNbEmpProsp.getText()), TxtCommentProsp.getText(), Integer.parseInt(TxtChiffAffProsp.getText()),
                    dateLocaleCrea, CmbBoxInteresse.getSelectedItem().toString());
                unProspModif.modification();
                showMessageDialog(null, "Le prospect " + TxtNumProsp.getText() + " a été modifié.");
            }
            this.dispose();
            new formAccueil().setVisible(true);
        }
        catch(Exception ex){
            showMessageDialog(null, ex.getMessage(), "Erreur", WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnConfirmProspActionPerformed

    //Bouton permettant de retourner à la page d'accueil
    private void BtnRetourProspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetourProspActionPerformed
        this.hide();
        formAccueil RetourFormAcc = new formAccueil();
        RetourFormAcc.setVisible(true);
    }//GEN-LAST:event_BtnRetourProspActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formProspect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formProspect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formProspect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formProspect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formProspect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConfirmProsp;
    private javax.swing.JButton BtnRetourProsp;
    private javax.swing.JComboBox<String> CmbBoxInteresse;
    private javax.swing.JComboBox<String> CmbBoxTypeProsp;
    private javax.swing.JLabel LabAdrClient;
    private javax.swing.JLabel LabChiffAffProsp;
    private javax.swing.JLabel LabCommentaireProsp;
    private javax.swing.JLabel LabDateProspection;
    private javax.swing.JLabel LabDateProspection2;
    private javax.swing.JLabel LabDomaineClient;
    private javax.swing.JLabel LabGestProsp;
    private javax.swing.JLabel LabInteresse;
    private javax.swing.JLabel LabNbrEmpProsp;
    private javax.swing.JLabel LabNumProsp;
    private javax.swing.JLabel LabRaisonSocialeProsp;
    private javax.swing.JLabel LabTelProsp;
    private javax.swing.JLabel LabTypeProsp;
    private javax.swing.JTextPane TxtAdrProsp;
    private javax.swing.JTextPane TxtChiffAffProsp;
    private javax.swing.JTextArea TxtCommentProsp;
    private javax.swing.JTextPane TxtDateProspection;
    private javax.swing.JTextPane TxtDomaineProsp;
    private javax.swing.JTextPane TxtNbEmpProsp;
    private javax.swing.JScrollPane TxtNbrEmpClient;
    private javax.swing.JTextPane TxtNumProsp;
    private javax.swing.JTextPane TxtRaisSocProsp;
    private javax.swing.JTextPane TxtTelProsp;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    // End of variables declaration//GEN-END:variables
}
